niche: motivational
theme: growth_mindset
language: en
duration: 60
style: cinematic
prompt:
  type: dynamic
  topic: "Discipline and Consistency"
  tone: inspirational
  emotion: high_energy
video:
  resolution: 1080x1920  # YouTube Shorts resolution (9:16 aspect ratio)
  format: mp4
  stitch_length: 8
voiceover:
  model: gemini_tts
  voice: deep_male
music:
  model: gemini_music
  mood: inspiring
  tempo: mid
subtitles:
  enable: true
  style: default
output:
  path: ./output/motivational/
  upload: true
  title: "Discipline and Consistency - Motivational Short #shorts"
  description: "Transform your life through discipline and consistency. Every small step counts towards your goals. #motivation #discipline #consistency #shorts #growth"
  tags: ["motivation", "discipline", "consistency", "growth", "shorts", "inspiration"]
  category_id: 22
  privacy_status: public 